---
apiVersion: tarantool.io/v1alpha1
kind: Cluster
metadata:
  name: tarantool-operator-app
spec:
  selector:
    matchLabels:
      tarantool.io/cluster-id: tarantool-operator-app
---
apiVersion: v1
kind: Service
metadata:
  name: main
  labels:
    tarantool.io/role: main
spec:
  ports:
    - port: 8081
      name: web
      protocol: TCP
    - port: 3301
      name: app
      protocol: TCP
  selector:
    tarantool.io/role: main
---
apiVersion: tarantool.io/v1alpha1
kind: Role
metadata:
  name: main
  labels:
    tarantool.io/cluster-id: tarantool-operator-app
    tarantool.io/role: main
  annotations:
    tarantool.io/rolesToAssign: "[\"vshard-router\", \"storage\"]"
spec:
  selector:
    matchLabels:
      tarantool.io/replicaset-template: "main-template"
  numReplicasets: 1
---
apiVersion: tarantool.io/v1alpha1
kind: ReplicasetTemplate
metadata:
  name: "main-template"
  labels:
    tarantool.io/cluster-id: tarantool-operator-app
    tarantool.io/replicaset-template: "main-template"
    tarantool.io/role: main
    tarantool.io/useVshardGroups: "0"
  annotations:
    tarantool.io/rolesToAssign: "[\"vshard-router\", \"storage\"]"
spec:
  replicas: 1
  serviceName: main
  selector:
    matchLabels:
      tarantool.io/pod-template: "main-pod-template"
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        tarantool.io/cluster-id: tarantool-operator-app
        tarantool.io/cluster-domain-name: "cluster.local"
        tarantool.io/pod-template: "main-pod-template"
        tarantool.io/useVshardGroups: "0"
        environment: "dev"
      annotations:
        tarantool.io/rolesToAssign: "[\"vshard-router\", \"storage\"]"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
    spec:
      terminationGracePeriodSeconds: 10
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      updateStrategy:
        type: OnDelete
      securityContext:
        fsGroup: 1000
        capabilities:
          add: ["SYS_ADMIN"]
      containers:
        - name: db
          image: "mikhailfilonenko/thestreets:latest"
          volumeMounts:
            - name: www
              mountPath: "/var/lib/tarantool"
          resources:
            requests:
              cpu: "0.1"
              memory: "256M"
            limits:
              cpu: "0.1"
              memory: "256M"
          ports:
            - containerPort: 3301
              protocol: TCP
              name: app
            - containerPort: 3301
              protocol: UDP
              name: app-udp
            - containerPort: 8081
              protocol: TCP
              name: http
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: TARANTOOL_INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TARANTOOL_ALIAS
              value: "$(TARANTOOL_INSTANCE_NAME)"
            - name: TARANTOOL_MEMTX_MEMORY
              value: "268435456"
            - name: TARANTOOL_BUCKET_COUNT
              value: "30000"
            - name: TARANTOOL_WORKDIR
              value: "/var/lib/tarantool"
            - name: TARANTOOL_ADVERTISE_TMP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TARANTOOL_ADVERTISE_HOST
              value: "$(TARANTOOL_ADVERTISE_TMP).tarantool-operator-app.sandbox.svc.cluster.local"
            - name: TARANTOOL_ADVERTISE_URI
              value: "$(TARANTOOL_ADVERTISE_HOST):3301"
            - name: TARANTOOL_PROBE_URI_TIMEOUT
              value: "60"
            - name: TARANTOOL_HTTP_PORT
              value: "8081"
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10

