---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarantool-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tarantool-operator
  template:
    metadata:
      labels:
        name: tarantool-operator
    spec:
      serviceAccountName: tarantool-operator
      imagePullSecrets:
        - name: ecr
      containers:
        - name: tarantool-operator
          image: tarantool/tarantool-operator:0.0.9
          command:
            - tarantool-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: tarantool-operator
              value: "tarantool-operator"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: tarantool-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - get
  - create
  - update
  - watch
  - list
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - get
  - create
  - update
  - watch
  - list
  - patch
  - delete
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - tarantool-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - tarantool.io
  resources:
  - clusters
  - roles
  - statefulsettemplatespecs
  - replicasettemplates
  verbs:
  - get
  - create
  - update
  - watch
  - list
  - patch
  - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tarantool-operator
subjects:
- kind: ServiceAccount
  name: tarantool-operator
roleRef:
  kind: Role
  name: tarantool-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tarantool-operator
---