# permissions for end users to view roles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-viewer-role
rules:
- apiGroups:
  - tarantool.io
  resources:
  - roles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tarantool.io
  resources:
  - roles/status
  verbs:
  - get
