[service]
dockerfile = 'build/Dockerfile'
eks_cluster = 'eks-prod'
namespace = 'userscripting'

regions = [
    'eu-west-1',
]

labels = [
    'environment:prod',
]

deployment.type = 'kubectl'
deployment.file = 'deploy/operator.yaml'

deployment.resources.cpu = '0.5'
deployment.resources.memory = '512M'
