name: Test
on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout 2m

  testing:
    name: testing
    runs-on: ubuntu-latest
    needs: lint
    env:
      OPERATOR_SDK_VERSION: v0.12.0
    
    strategy:
      matrix:
        kubernetes-version: [1.16.4, 1.19.4, 1.22.4]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    # - name: Set up Kind k8s Cluster
    #   uses: helm/kind-action@v1.1.0
    #   with:
    #     node_image: kindest/node:v${{ matrix.kubernetes-version }}

    - name: Set up Kubebuilder
      run: |
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        ARCH=$(uname -m | sed 's/x86_64/amd64/')
        curl -fsL "https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-${{matrix.kubernetes-version}}-${{OS}}-${{ARCH}}.tar.gz" \
          -o kubebuilder-tools
        tar -zvxf kubebuilder-tools
        sudo mv kubebuilder/ /usr/local/kubebuilder

    - name: Test
      run: make test
